INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Industry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Functionality', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hiking Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Soft Drinks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Dish Detergents', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cereals', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Analgesics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bottled Juices', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Canned Soups', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cheeses', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Paper Towels', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tooth Pastes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Canned Fish', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Frozen Entrees', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Snack Crackers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lip Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hairspray', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hair Conditioner', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby products', NOW());
